### ISSUE TITLE
Update Ordeal pages w/ 2018 Info

### ISSUE THREAD

**Issue by pearatme** [col-bsa/Unami-Lodge-Documentation#13]
**Owner / Committee:**
Communications

**Due Date:**
Soon

**Description:**
Unit Elections are starting soon so it would be good to update the ordeal information/candidate pages

**Tasks:** 
- [x] Update Ordeal Information Page
- [x] Update Ordeal Candidate Page
- [x] Ask for a Summer Camp Ordeal sign up link
- [x] Add provisional Summer Camp Ordeal Link back into Ordeal Candidate Page
