### ISSUE TITLE
Update Constellation Leadership

### ISSUE THREAD

**Issue by pearatme** [col-bsa/Unami-Lodge-Documentation#14]
**Owner / Committee:**
Communications

**Due Date:**
Soon

**Description:**
An email recently informed Communications in a change in leadership; this issue should address those changes

**Tasks:** 
- [x] Replace Constellation Chapter Chief Position with Andrew Geer
- [x] Change Constellation Vice-Chapter Chief Position to Vacant
- [x] Remove Andrew McGee's email from @unamilodge.org
