### ISSUE TITLE
Fix notices on contact pages

### ISSUE THREAD

**Issue by pearatme** [col-bsa/Unami-Lodge-Documentation#15]
**Owner / Committee:**
Communications

**Due Date:**
Soon

**Description:**
The [Contact Splash Page](https://dev.unamilodge.org/contact-splash) and the [Contact Page](https://dev.unamilodge.org/contact.php?recip=communications) have notices that can be removed.

**Tasks:** 
- [x] Fix notice in contact.php on line 4
- [x] Fix notice in contact.php on line 11
- [x] Fix notice in contact-splash.php on line 9
- [x] Fix notice in contact-splash.php on line 12
