### ISSUE TITLE
Add Articles for Events to Front Page

### ISSUE THREAD

**Issue by pearatme** [col-bsa/Unami-Lodge-Documentation#17]
**Owner / Committee:**
Communications

**Due Date:**
Soon

**Description:**
There needs to be Service Day, and Conclave promotion articles on the website

**Tasks:** 
- [x] Write an article for Conclave
- [x] Write an article for Service Day
- [x] Get Conclave Article Approved

**Comment by crossfireprod** [comment]
I hadn't given this any thought until now; how do we want to handle issue tracking with regard to "complete, but still stuck in dev" vs "dev merged to prod, changes live?"

(Cause it looks like this one is still in dev purgatory.)

@pearatme 
@mngutterman 
@dwgibbons

**Comment by crossfireprod** [comment]
...I'm personally gonna vote:
- No change is too small to merge to prod, I see no reason to "queue up a bunch of commits."
- Issues don't get closed until whatever changes were made are live and spot checked in prod.
