### ISSUE TITLE
General Updates

### ISSUE THREAD

**Issue by pearatme** [col-bsa/Unami-Lodge-Documentation#18]
**Owner / Committee:**
Communications

**Due Date:**
Soon

**Description:**
Service asked us to update the article on the front page.
Update Service Article on Unami Update as well.
Conestoga Chapter page needs to be updated, because they got a new Vice Chief.

**Tasks:** 
- [x] Update Service Article on Front Page.
- [x] Update Service Article on Unami Update.
- [x] Update Conestoga Chapter Page.
