### ISSUE TITLE
Update Front Page and Links Page 

### ISSUE THREAD

**Issue by pearatme** [col-bsa/Unami-Lodge-Documentation#19]
**Owner / Committee:**
Communications

**Due Date:**
Soon

**Description:**

**Tasks:** 
- [x] Add Council Dinner article to the front page.
- [x] Add SS2 link to the front page
- [x] Add Vigil article to the front page
- [x] Fix Issues on links page including Lodge Names, and removal of resource sections.
- [x] Update CSD.
