### ISSUE TITLE
Create New Email Accounts

### ISSUE THREAD

**Issue by mngutterman** [col-bsa/Unami-Lodge-Documentation#2]
**Owner / Committee:**
Communications

**Due Date:**
1/13/2018

**Description:**
Create individual email accounts for new lec members.

**Tasks:** 
- [ ] Create new email accounts for new lec members
- [ ] Inform new members of their new accounts and how to access
- [ ] **DO NOT** assign new accounts to any groups

**Comment by mngutterman** [comment]
Added '2018 LEC Sign In Sheets' to the communications team drive to track account creation.

**Comment by mngutterman** [comment]
Transitioning all old accounts to 'firstname.lastname@ul.org' format as well.  Google Apps automatically preserves the former account name as an alias.

**Comment by crossfireprod** [comment]
This is done
