### ISSUE TITLE
Fix TheScoutmaster

### ISSUE THREAD

**Issue by dwgibbons** [col-bsa/Unami-Lodge-Documentation#24]
**Owner / Committee:**
Communications

**Due Date:**
2/4/2019

**Description:**
Known bugs listed as tasks

**Tasks:** 
- [ ] Fix digitalocean task droplet creation arguments
- [ ] Fix PHP versioning
- [ ] Update to newest droplet sizes and appropriate distributions
