### ISSUE TITLE
Transition Email Groups

### ISSUE THREAD

**Issue by mngutterman** [col-bsa/Unami-Lodge-Documentation#3]
**Owner / Committee:**
Communications

**Due Date:**
1/15/2018

**Description:**
Transition email groups to 2018 LEC members

**Tasks:** 
- [x] Inform current LEC of transition through email
- [x] Remove all current members of a group
- [x] Add all new members
- [x] Update [LEC Contact Page](http://unamilodge.org/lec-contacts) on website
