### ISSUE TITLE
Update LEC Contacts & Officers Pages w/ 2018 Info

### ISSUE THREAD

**Issue by crossfireprod** [col-bsa/Unami-Lodge-Documentation#7]
**Owner / Committee:**
Communications

**Due Date:**
08Jan17

**Description:**
Update the following pages to reflect 2018 information in spreadsheet from Dennis:
http://unamilodge.org/lec-officers
http://unamilodge.org/lec-contacts

**Tasks:** 
- [x] Update lec-officers in dev branch.
- [x] Update lec-contacts in dev branch
- [x] Merge changes to master branch following the lodge dinner on 07Jan17.

**Comment by crossfireprod** [comment]
@pearatme - Looks great!  We'll merge these changes into master on Sunday night right after the dinner.
