### ISSUE TITLE
Update Chapters pages w/ 2018 Info

### ISSUE THREAD

**Issue by crossfireprod** [col-bsa/Unami-Lodge-Documentation#8]
**Owner / Committee:**
Communications

**Due Date:**
08Jan17

**Description:**
Update the chapters pages to reflect 2018 information in spreadsheet from Dennis:
http://unamilodge.org/chapter
https://github.com/col-bsa/UnamiLodge.org/blob/master/chapter.php

**Tasks:** 
- [x] Update "chapter.php" officer info in dev branch.
- [x] Merge changes to master branch following the lodge dinner on 07Jan17.
- [x] Reach out to VC Chapters to confirm meeting time / location details.

**Comment by crossfireprod** [comment]
Officers updated; @pearatme still working to confirm meeting details w/ VC Chapters.
